theme = 'rose_pine_transparent'

[editor]
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true

[keys.normal]
C-c = "normal_mode" # i spam ctrl-c a lot :\
C-s = ":w"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-r = ":reflow 81"
A-r = ":rl"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"

